queue_rules:
  - name: default
    conditions:
      - status-success=lint-markdown / lint-markdown
      - status-success=commit-checks / version
      - status-success=rust-checks / check
      - status-success=rust-checks / test (macos-latest)
      - status-success=rust-checks / test (ubuntu-latest)
      - status-success=rust-checks / test (windows-latest)
      - status-success=rust-checks / lints (macos-latest)
      - status-success=rust-checks / lints (ubuntu-latest)
      - status-success=rust-checks / lints (windows-latest)
      - status-success=rust-checks / security-audit
      - status-success=rust-checks / bench (macos-latest)
      - status-success=rust-checks / bench (ubuntu-latest)
      - status-success=rust-checks / bench (windows-latest)

pull_request_rules:
  - name: request review on external contributor
    conditions:
      - -author=PurpleBooth
    actions:
      assign:
        add_users:
          - PurpleBooth

  - name: automatic rebase for dependencies
    conditions:
      - status-success=lint-markdown / lint-markdown
      - status-success=commit-checks / version
      - status-success=rust-checks / check
      - status-success=rust-checks / test (macos-latest)
      - status-success=rust-checks / test (ubuntu-latest)
      - status-success=rust-checks / test (windows-latest)
      - status-success=rust-checks / lints (macos-latest)
      - status-success=rust-checks / lints (ubuntu-latest)
      - status-success=rust-checks / lints (windows-latest)
      - status-success=rust-checks / security-audit
      - status-success=rust-checks / bench (macos-latest)
      - status-success=rust-checks / bench (ubuntu-latest)
      - status-success=rust-checks / bench (windows-latest)
      - base=main
      - author~=^dependabot(|-preview)\[bot\]$
    actions:
      queue:
        method: rebase
        rebase_fallback: merge
        name: default
