name: automerge
on:
  check_suite:
    types:
      - completed
  status: {}
jobs:
  dependency-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@7ab42e888a333bf77ce865bc84fedc6a365a3548"
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
          MERGE_METHOD: rebase
          MERGE_LABELS: "dependencies"
          MERGE_DELETE_BRANCH: true
  release-automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@7ab42e888a333bf77ce865bc84fedc6a365a3548"
        env:
          GITHUB_TOKEN: "${{ secrets.COMMITTER_TOKEN }}"
          MERGE_METHOD: rebase
          MERGE_LABELS: "release"
          MERGE_DELETE_BRANCH: true
          UPDATE_METHOD: "rebase"
          UPDATE_LABELS: "release"


